# -*- coding: utf-8 -*-
"""Fellowship_Task1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/ahsanatiq05/BuildablesDataScienceFellowship/blob/main/Fellowship_Task1.ipynb

#**Day-1**

### Question 1
"""

a = int(input("Enter first the number: "))
b = int(input("Enter the second number:"))
print("The sum is " + str(a+b))

"""## Question 2"""

r = int(input("Enter the radius: "))
print("The raidus of the circle is: " + str(3.14 * r**2))

"""## Question 3"""

a = int(input("Enter the number: "))
if a % 2 == 0:
  print("The number is even")
else:
  print("The number is odd")

"""## Question 4"""

a = int(input("Enter the first number: "))
b = int(input("Enter the second number: "))
c = str(input("Enter the operator: "))

if (c == "+"):
  print("The result is:" + str(a+b))
elif (c == "-"):
  print("The result is:" + str(a-b))
elif (c == "*"):
  print("The result is:" + str(a*b))
elif (c == "/"):
  print("The result is:" + str(a/b))
else:
  print("Invalid operator")

"""##Question 5"""

a = int(input("Enter the first number: "))
b = int(input("Enter the second number: "))
c = int(input("Enter the third number: "))

if (a> b and a>c):
  print("The largest number is: " + str(a))
elif (b>a and b>c):
  print("The largest number is: " + str(b))
else:
  print("The largest number is: " + str(c))

"""##Question 6"""

s = str(input("Enter the string: "))
t = ""
for i in range(len(s)-1, -1, -1):
  t = t + s[i]
print(t)

"""##Question 7"""

s = str(input("Enter the string: "))
s.lower()
count = 0;
for i in range(len(s)):
  if (s[i] == "a" or s[i] == "e" or s[i] == "i" or s[i] == "o" or s[i] == "u"):
    count = count +1
print("The number of vowels is: " + str(count))

"""## Question 8"""

n = int(input("Enter the number: "))
p = 0
c = 0
for i in range(n):
  if i == 0:
    print(0)
  elif i == 1:
    print(1)
    c = 1
  else:
     z = c +p
     print(z)
     p = c
     c = z

"""## Question 9"""

s = str(input("Enter the string: "))
i = 0
j = len(s)-1
check = True
while(i<j):
  if s[i] != s[j]:
    print(s + " is not plaindrome")
    check = False
    break;
  i = i+1
  j = j-1
if(check):
  print(s + " is plaindrome")
